- type: choice
  difficulty: 5
  timeout: 10
  prompt: You found an archive that seems to may contain sensitive data. Which of the commands will extract it?
  choices:
    a: tar -xzf archive.tar.gz
    b: echo archive.tar.gz | unpack
    c: untar archive.tar.gz
    d: mv archive.tar.gz unpacked
  solution: a

- type: question
  timeout: 30
  difficulty: 6
  promt: |
    While reverse engineering the security program of your target you found a Javascript function. What input would be required to make it return false?

    const superSecureCheck = number => {
      let value = number - 15;

      return !!value
    };
  solution: 15

- type: question
  prompt: |
    Which input is required to make this function return 42?

    fn (int input) => (input - 2) * 2
  solution: 23

- type: question
  prompt: What is the answer?
  solution: 42

- type: question
  prompt: Who is spying on Alice and Bob?
  solution: Eve

- type: scriptkiddie
  timeout: 10
  required_characters: 50

- type: scriptkiddie
  timeout: 11
  required_characters: 75

- type: scriptkiddie
  timeout: 12
  required_characters: 100

- type: scriptkiddie
  timeout: 13
  required_characters: 150

- type: scriptkiddie
  timeout: 14
  required_characters: 200

- type: scriptkiddie
  timeout: 15
  required_characters: 250

- type: regex
  timeout: 20
  difficulty: 5
  prompt: You need to choose a username for your secret H4xX0R user but the admin only allows usernames that match a specific pattern
  regex: user-[0-9]{3,5}

- type: regex
  prompt: foo?
  regex: f[o]{2}ba[rz]

- type: regex
  prompt: Where was this game made?
  regex: ([GJ](lobal|ame?)| ){5}

- type: regex
  prompt: What's the time?
  regex: [0-9]\\d:[:digit:]{2}

- type: regex
  prompt: Hi there!
  regex: Hello [a-zA-Z]+!

- type: regex
  prompt: What's your address?
  regex: ([0-9a-f]{2}:){5}[0-9a-f]{2}

- type: regex
  prompt: What's your address?
  regex: (([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])

- type: regex
  prompt: What's your address?
  regex: (([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))

- type: regex
  prompt: The best homepage?
  regex: https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#()?&//=]*)

